baseURL = 'https://869413421.github.io/'
languageCode = 'en-zh'
title = '清水泥沙'
theme = "paper"

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = '869413421'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = '清水泥沙'
  bio = ''


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

[[menu.main]]
    identifier = "about"
    pre = ""
    name = "个人简历"
    url = "/about/"
    title = ""
    weight = 4	
    
[[menu.main]] 
	identifier = "categories" 
	pre = "" 
	name = "分类" 
	url = "/categories" 
	title = "" 
	weight = 3
	
[[menu.main]] 
	identifier = "tags" 
	pre = "" 
	name = "标签" 
	url = "/tags" 
	title = "" 
	weight = 2